// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxfucsaskcbmwuenbvna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4ZnVjc2Fza2NibXd1ZW5idm5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODUyOTAsImV4cCI6MjA2NTQ2MTI5MH0.ULh-VdcHu9BJpvU1-ZpEqUobyBDun0UF73yFhdngHB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);